server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
      
      
#zuul:
#  routes:
#    EmployeeService:
#      url: http://localhost:8082
      
      
#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000
  
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: THREAD
#          thread:
#            timeoutInMilliseconds: 60000